import { ArrowRight, Calculator } from "lucide-react";
import { articleIds, articlePath, getArticle, type ArticleId } from "@/lib/articles";
import { getCountry } from "@/lib/countries";
import { countryName, localizedPath, type Locale } from "@/lib/i18n";
import { calculate } from "@/lib/tax-engine";
import { authorityPath } from "@/lib/authority";
import { locales, SITE_URL } from "@/lib/seo";

const localeTags:Record<Locale,string>={en:"en-US",es:"es-ES",de:"de-DE",fr:"fr-FR"};
const labels:Record<Locale,{guides:string;calculator:string;estimate:string;related:string;method:string;external:string}>={
 en:{guides:"Salary guides",calculator:"Open Germany salary calculator",estimate:"Live calculator example",related:"Related guides",method:"Read the calculation methodology",external:"Practical Germany guides"},
 es:{guides:"Guías salariales",calculator:"Abrir calculadora de Alemania",estimate:"Ejemplo calculado en directo",related:"Guías relacionadas",method:"Leer la metodología de cálculo",external:"Guías prácticas de Alemania"},
 de:{guides:"Gehaltsratgeber",calculator:"Deutschland-Rechner öffnen",estimate:"Live berechnetes Beispiel",related:"Weitere Ratgeber",method:"Berechnungsmethodik lesen",external:"Praktische Deutschland-Guides"},
 fr:{guides:"Guides salariaux",calculator:"Ouvrir le calculateur Allemagne",estimate:"Exemple calculé en direct",related:"Guides associés",method:"Lire la méthodologie",external:"Guides pratiques sur l’Allemagne"},
};

export function ArticlePage({id,locale}:{id:ArticleId;locale:Locale}){
 const article=getArticle(id,locale);const t=labels[locale];const germany=getCountry("germany");const spain=getCountry("spain");
 const gross=id==="salary-3000"?3000:id==="minimum-wage"?germany.minimum!*40*52/12:3200;
 const germanResult=calculate(germany,gross,"monthly",40);const spanishResult=calculate(spain,gross,"monthly",40);
 const money=(value:number,currency:string)=>new Intl.NumberFormat(localeTags[locale],{style:"currency",currency,maximumFractionDigits:0}).format(value);
 const path=articlePath(id,locale);
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"Article",headline:article.title,description:article.description,inLanguage:locale,datePublished:"2026-10-01",dateModified:"2026-10-01",mainEntityOfPage:`${SITE_URL}${path}`,author:{"@type":"Person",name:"Héctor Fàbrega Roig"},publisher:{"@type":"Organization",name:"Net Salary Map",url:SITE_URL}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Net Salary Map",item:`${SITE_URL}${localizedPath(germany,locale)}`},{"@type":"ListItem",position:2,name:t.guides,item:`${SITE_URL}${path}`},{"@type":"ListItem",position:3,name:article.title,item:`${SITE_URL}${path}`}]},{"@type":"FAQPage",mainEntity:article.faq.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))}]};
 return <div className="min-h-screen overflow-x-clip bg-[#f6f8fc] text-slate-950"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-3 px-4 py-4 sm:px-5"><a href={localizedPath(germany,locale)} className="flex min-w-0 items-center gap-3 font-black"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-blue-600 text-white"><Calculator className="size-5"/></span><span className="hidden truncate sm:inline">Net Salary Map</span></a><nav aria-label="Language" className="flex items-center gap-1">{locales.map(item=><a key={item} href={articlePath(id,item)} lang={item} className={`rounded-lg px-2 py-1 text-xs font-bold uppercase ${item===locale?"bg-blue-600 text-white":"text-slate-500 hover:bg-slate-100"}`}>{item}</a>)}</nav><a href={localizedPath(germany,locale)} className="hidden shrink-0 text-sm font-bold text-blue-700 md:block">{t.calculator}</a></div></header>
 <main className="mx-auto max-w-4xl px-4 py-10 sm:px-5 sm:py-16"><nav aria-label="Breadcrumb" className="mb-7 text-sm font-semibold text-slate-500"><a href={localizedPath(germany,locale)}>Net Salary Map</a><span className="px-2">/</span><span>{t.guides}</span></nav><article className="rounded-[28px] border bg-white p-6 shadow-sm sm:p-10"><p className="text-xs font-bold uppercase tracking-widest text-blue-600">{t.guides} · 2026</p><h1 className="mt-3 text-balance text-4xl font-black sm:text-5xl">{article.title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{article.intro}</p><a href={localizedPath(germany,locale)} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">{t.calculator}<ArrowRight className="size-4"/></a>
 <section className="my-9 rounded-2xl bg-[#101c3b] p-5 text-white sm:p-7"><p className="text-sm font-bold text-blue-200">{t.estimate}</p><div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2"><div><span className="text-sm text-slate-300">{money(gross,"EUR")} {locale==="es"?"brutos/mes":locale==="de"?"brutto/Monat":locale==="fr"?"brut/mois":"gross/month"}</span><b className="mt-1 block text-3xl">{money(germanResult.net,"EUR")}</b><span className="text-sm text-slate-300">{countryName(germany,locale)}</span></div>{id==="germany-spain"?<div><span className="text-sm text-slate-300">{money(gross,"EUR")} {locale==="es"?"brutos/mes":locale==="de"?"brutto/Monat":locale==="fr"?"brut/mois":"gross/month"}</span><b className="mt-1 block text-3xl">{money(spanishResult.net,"EUR")}</b><span className="text-sm text-slate-300">{countryName(spain,locale)}</span></div>:<div><span className="text-sm text-slate-300">{locale==="es"?"Neto anual":locale==="de"?"Jahresnetto":locale==="fr"?"Net annuel":"Annual net"}</span><b className="mt-1 block text-3xl">{money(germanResult.annualNet,"EUR")}</b><span className="text-sm text-slate-300">{germanResult.keep.toFixed(1)}%</span></div>}</div></section>
 <div className="space-y-9">{article.sections.map(section=><section key={section.heading}><h2 className="text-2xl font-black">{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph} className="mt-3 leading-7 text-slate-600">{paragraph}</p>)}</section>)}</div>
 <section className="mt-10 border-t pt-8"><h2 className="text-2xl font-black">FAQ</h2>{article.faq.map(item=><details key={item.question} className="border-b py-4"><summary className="cursor-pointer font-bold">{item.question}</summary><p className="mt-2 leading-7 text-slate-600">{item.answer}</p></details>)}</section>
 <aside className="mt-9 rounded-2xl bg-blue-50 p-5"><a className="font-bold text-blue-800 underline underline-offset-4" href={authorityPath(locale,"methodology")}>{t.method}</a><p className="mt-3 text-sm leading-6 text-blue-950/75">{locale==="es"?"Para vivienda, trabajo y trámites, consulta":locale==="de"?"Für Wohnen, Arbeit und Behörden siehe":locale==="fr"?"Pour logement, travail et démarches, consultez":"For housing, work and relocation, see"} <a className="font-bold underline" href="https://germanybase.de/guides/working-in-germany" target="_blank" rel="noopener noreferrer">{t.external}</a>.</p></aside>
 </article><section className="mt-8"><h2 className="text-xl font-black">{t.related}</h2><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">{articleIds.filter(item=>item!==id).slice(0,4).map(item=><a key={item} href={articlePath(item,locale)} className="rounded-2xl border bg-white p-4 font-bold shadow-sm hover:border-blue-300">{getArticle(item,locale).title}</a>)}</div></section></main></div>;
}
