"use client";

import { useEffect, useMemo, useState } from "react";
import { Calculator, ChevronDown, Globe2, Search, ShieldCheck, Sparkles } from "lucide-react";
import { countries, type Country } from "@/lib/countries";
import { countryName, localizedPath, type Locale } from "@/lib/i18n";
import { uiText, type UiText } from "@/lib/translations";
import { calculate, type PrecisionOptions } from "@/lib/tax-engine";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { legalNavLabels, legalPath, type LegalKind } from "@/lib/legal-routes";
import { faqLabels } from "@/lib/faq-labels";
import { countryNote } from "@/lib/country-notes";
import { authorityLabels, authorityPath, type AuthorityKind } from "@/lib/authority";

const localeTags: Record<Locale, string> = { en: "en-US", es: "es-ES", de: "de-DE", fr: "fr-FR" };
function money(value:number,c:Country,language:Locale,digits=0){return new Intl.NumberFormat(localeTags[language],{style:"currency",currency:c.currency,maximumFractionDigits:digits}).format(value)}

export function SalaryCalculator({country,language,heading,intro,specificFaq,seoContent}:{country:Country;language:Locale;heading:string;intro:string;specificFaq:string;seoContent?:React.ReactNode}){
 const t=uiText[language];
 const [salary,setSalary]=useState(3200); const [period,setPeriod]=useState<"monthly"|"annual">("monthly"); const [hours,setHours]=useState(40); const [more,setMore]=useState(false); const [query,setQuery]=useState("");
 const [precision,setPrecision]=useState<PrecisionOptions>({age:30,children:0,marital:"single",taxClass:"1",church:false,germanState:"standard",health:"public",spainRegion:"average",contract:"permanent",filingStatus:"single",stateRate:0,canton:"average",province:"ontario"});
 const updatePrecision=<K extends keyof PrecisionOptions>(key:K,value:PrecisionOptions[K])=>setPrecision(current=>({...current,[key]:value}));
 const result=useMemo(()=>calculate(country,salary,period,hours,precision),[country,salary,period,hours,precision]);
 const grossHourly=(period==="monthly"?salary*12:salary)/(Math.max(hours,1)*52);
 const minHourly=country.minimum ? country.minimumPeriod==="hour"?country.minimum:(country.minimum*(country.minimumPayments??12))/(40*52):undefined;
 const filtered=countries.filter(c=>countryName(c,language).toLowerCase().includes(query.toLowerCase()));
 const navigate=(id:string)=>{const c=countries.find(x=>x.id===id)!; window.location.href=localizedPath(c,language)};
 const examples=[2000,3200,5000].map(v=>({v,r:calculate(country,v,"monthly",40)}));
 useEffect(()=>{document.documentElement.lang=language},[language]);
 return <div className="min-h-screen w-full min-w-0 overflow-x-clip bg-[#f6f8fc] text-[#111827]">
  <header className="sticky top-0 z-40 w-full border-b border-slate-200/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex min-w-0 max-w-7xl items-center justify-between gap-3 px-4 py-4 sm:px-5 lg:px-8"><a href={localizedPath(country,language)} className="flex min-w-0 flex-1 items-center gap-2.5 sm:gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#2155f5] text-white shadow-lg shadow-blue-200"><Calculator className="size-5"/></span><span className="min-w-0"><b className="block truncate text-base leading-none tracking-tight sm:text-lg">{t.brand}</b><small className="mt-1 block truncate text-[11px] text-slate-500 sm:text-xs">{t.tag}</small></span></a><div className="flex shrink-0 items-center gap-2"><span className="hidden rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700 sm:inline-flex"><ShieldCheck className="mr-1 size-3.5"/>{t.data}</span><select aria-label="Language" value={language} onChange={e=>{window.location.href=localizedPath(country,e.target.value as Locale)}} className="max-w-20 rounded-xl border bg-white px-2.5 py-2 text-sm font-semibold shadow-sm sm:max-w-none sm:px-3"><option value="en">EN</option><option value="es">ES</option><option value="de">DE</option><option value="fr">FR</option></select></div></div></header>
  <main>
   <section className="mx-auto w-full min-w-0 max-w-7xl px-4 pb-12 pt-7 sm:px-5 lg:px-8 lg:pt-12"><nav aria-label="Breadcrumb" className="mb-7 min-w-0 text-sm font-semibold text-slate-500"><a href="/" className="hover:text-blue-700">Net Salary Map</a><span className="px-2">/</span><span className="break-words">{countryName(country,language)}</span></nav><div className="mb-9 min-w-0 max-w-4xl"><div className="mb-3 inline-flex max-w-full items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700"><Sparkles className="size-3.5 shrink-0"/><span className="truncate">{country.flag} {countryName(country,language)} · 2026</span></div><h1 className="text-balance break-words text-4xl font-black sm:text-6xl">{heading}</h1><p className="mt-4 break-words text-xl font-bold text-slate-700">{t.title}</p><p className="mt-3 max-w-3xl break-words text-base leading-7 text-slate-600">{intro}</p></div>
   <div className="grid min-w-0 grid-cols-1 items-start gap-6 lg:grid-cols-[1.02fr_.98fr]">
    <div className="min-w-0 overflow-hidden rounded-[28px] border border-slate-200 bg-white p-5 shadow-[0_24px_70px_rgba(39,54,89,.10)] sm:p-7"><div className="grid min-w-0 grid-cols-1 gap-5 sm:grid-cols-2"><label className="block min-w-0 max-w-full sm:col-span-2"><span className="mb-2 block text-sm font-bold">{t.country}</span><Select value={country.id} onValueChange={navigate}><SelectTrigger className="h-14 min-w-0 w-full max-w-full rounded-xl border-slate-200 bg-slate-50 px-4 text-base"><SelectValue/></SelectTrigger><SelectContent>{countries.map(c=><SelectItem key={c.id} value={c.id}>{c.flag} {countryName(c,language)}</SelectItem>)}</SelectContent></Select></label>
    <label className="block min-w-0 max-w-full sm:col-span-2"><span className="mb-2 block text-sm font-bold">{t.gross}</span><div className="flex h-16 min-w-0 max-w-full overflow-hidden rounded-xl border border-slate-200 bg-slate-50 focus-within:ring-4 focus-within:ring-blue-100"><span className="grid w-14 shrink-0 place-items-center border-r text-lg font-black text-slate-500">{country.symbol}</span><input aria-label={t.gross} className="w-0 min-w-0 flex-1 bg-transparent px-4 text-2xl font-black outline-none" inputMode="decimal" value={salary} onChange={e=>setSalary(Number(e.target.value)||0)}/></div></label>
    <div className="grid min-w-0 max-w-full grid-cols-2 rounded-xl bg-slate-100 p-1 sm:col-span-2"><button onClick={()=>setPeriod("monthly")} className={`min-w-0 rounded-lg py-3 text-sm font-bold transition ${period==="monthly"?"bg-white text-blue-700 shadow-sm":"text-slate-500"}`}>{t.monthly}</button><button onClick={()=>setPeriod("annual")} className={`min-w-0 rounded-lg py-3 text-sm font-bold transition ${period==="annual"?"bg-white text-blue-700 shadow-sm":"text-slate-500"}`}>{t.annual}</button></div>
    <label className="block min-w-0 max-w-full sm:col-span-2"><span className="mb-2 block text-sm font-bold">{t.hours}</span><input aria-label={t.hours} className="h-12 w-full min-w-0 max-w-full rounded-xl border border-slate-200 bg-slate-50 px-4 font-semibold outline-none focus:ring-4 focus:ring-blue-100" type="number" min="1" max="100" value={hours} onChange={e=>setHours(Number(e.target.value)||0)}/></label></div>
    <Collapsible open={more} onOpenChange={setMore} className="mt-5 border-t pt-5"><CollapsibleTrigger className="flex w-full items-center justify-between text-sm font-extrabold text-blue-700">{t.precise}<ChevronDown className={`size-4 transition ${more?"rotate-180":""}`}/></CollapsibleTrigger><CollapsibleContent className="pt-4"><PrecisionFields country={country} t={t} value={precision} update={updatePrecision}/></CollapsibleContent></Collapsible>
    </div>
    <div className="min-w-0 overflow-hidden rounded-[28px] bg-[#101c3b] text-white shadow-[0_26px_80px_rgba(18,31,67,.28)]"><div className="min-w-0 p-5 sm:p-8"><p className="text-sm font-semibold text-blue-200">{t.net}</p><p className="mt-1 break-words text-4xl font-black sm:text-6xl">{money(result.net,country,language)}</p><p className="mt-2 text-sm text-slate-300">/{period==="monthly"?t.monthly.toLowerCase():t.annual.toLowerCase()}</p><div className="mt-7 grid min-w-0 grid-cols-2 gap-3"><Metric label={t.annualNet} value={money(result.annualNet,country,language)}/><Metric label={t.hour} value={result.hourly?money(result.hourly,country,language,2):"—"}/><Metric label={t.deductions} value={money(result.deductions,country,language)}/><Metric label={t.keep} value={`${result.keep.toFixed(1)}%`}/></div><div className="mt-7"><div className="mb-2 flex justify-between gap-3 text-xs font-bold"><span>{t.netLabel}</span><span className="text-right">{t.deductionsLabel}</span></div><div className="flex h-3 overflow-hidden rounded-full bg-white/10"><span className="bg-[#4f7cff]" style={{width:`${result.keep}%`}}/><span className="flex-1 bg-[#ffba52]"/></div></div></div><div className="min-w-0 border-t border-white/10 bg-white/[.04] p-5 sm:p-8"><h2 className="mb-4 break-words font-black">{t.breakdown}</h2><Row label={t.gross} value={money(salary,country,language)}/>{result.breakdown.map(x=><Row key={x.label} label={`− ${language==="es"?x.es:language==="de"?x.de:language==="fr"?x.fr:x.label}`} value={money(x.amount,country,language)}/>) }<div className="mt-3 border-t border-white/10 pt-3"><Row label={`= ${t.net}`} value={money(result.net,country,language)} strong/></div></div></div>
   </div></section>
   <section className="mx-auto w-full min-w-0 max-w-7xl px-4 pb-10 sm:px-5 lg:px-8"><div className="min-w-0 rounded-2xl border border-dashed border-slate-300 bg-white px-3 py-5 text-center text-xs font-bold uppercase tracking-[.14em] text-slate-400 sm:tracking-[.18em]">{t.ad}</div></section>
   {seoContent}
   <section className="mx-auto grid w-full min-w-0 max-w-7xl grid-cols-1 gap-6 px-4 py-8 sm:px-5 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="min-w-0 rounded-3xl border bg-white p-5 shadow-sm sm:p-6"><div className="mb-4 flex min-w-0 items-center gap-2"><Globe2 className="size-5 shrink-0 text-blue-600"/><h2 className="min-w-0 break-words text-xl font-black">{t.explore}</h2></div><div className="relative mb-4 min-w-0"><Search className="absolute left-3 top-3.5 size-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} className="h-11 w-full min-w-0 rounded-xl border bg-slate-50 pl-10 pr-3 outline-none focus:ring-4 focus:ring-blue-100"/></div><div className="worldmap relative h-56 min-w-0 overflow-hidden rounded-2xl bg-[#eef4ff]">{countries.map(c=><a title={countryName(c,language)} aria-label={countryName(c,language)} key={c.id} href={localizedPath(c,language)} className={`absolute grid size-5 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-white bg-blue-600 shadow transition hover:z-10 hover:scale-150 ${c.id===country.id?"ring-4 ring-amber-300":""}`} style={{left:`${c.x}%`,top:`${c.y}%`}}><span className="sr-only">{countryName(c,language)}</span></a>)}</div><div className="mt-4 grid min-w-0 max-h-52 grid-cols-1 gap-1 overflow-auto pr-1 text-sm min-[360px]:grid-cols-2">{filtered.map(c=><a className={`min-w-0 break-words rounded-lg px-3 py-2 font-semibold hover:bg-blue-50 ${c.id===country.id?"bg-blue-50 text-blue-700":""}`} key={c.id} href={localizedPath(c,language)}>{c.flag} {countryName(c,language)}</a>)}</div></div>
   <div className="min-w-0 space-y-6"><article className="min-w-0 rounded-3xl border bg-white p-5 shadow-sm sm:p-6"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">{t.min}</p><h2 className="mt-2 break-words text-2xl font-black">{country.minimum?`${money(country.minimum,country,language,2)} / ${country.minimumPeriod==="hour"?t.hourUnit:t.monthUnit}`:t.noMinimum}</h2>{minHourly&&hours>0?<p className={`mt-3 rounded-xl p-3 text-sm font-semibold ${grossHourly<minHourly?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{grossHourly<minHourly?t.below:t.above}</p>:null}{countryNote(country,language)?<p className="mt-3 text-sm leading-6 text-slate-600">{countryNote(country,language)}</p>:null}</article>
   <article className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">{t.examples}</h2><div className="mt-4 divide-y">{examples.map(x=><div key={x.v} className="flex justify-between py-3 text-sm"><span>{money(x.v,country,language)} {t.grossShort}</span><b>{money(x.r.net,country,language)} {t.netShort}</b></div>)}</div></article></div></section>
   <section className="mx-auto w-full min-w-0 max-w-7xl px-4 py-10 sm:px-5 lg:px-8"><div className="grid min-w-0 grid-cols-1 gap-6 lg:grid-cols-2"><article className="min-w-0 rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="break-words text-2xl font-black">{t.how}</h2><p className="mt-3 break-words leading-7 text-slate-600">{t.copy}</p><div className="mt-6 grid min-w-0 grid-cols-1 gap-3 text-sm min-[360px]:grid-cols-2"><div className="min-w-0 rounded-xl bg-slate-50 p-4"><span className="block break-words text-slate-500">{t.taxYear}</span><b>2026</b></div><div className="min-w-0 rounded-xl bg-slate-50 p-4"><span className="block break-words text-slate-500">{t.updated}</span><b>1 Oct 2026</b></div></div><a className="mt-5 inline-flex max-w-full break-words font-bold text-blue-700 underline decoration-blue-200 underline-offset-4" href={authorityPath(language,"methodology")}>{t.method}</a></article><article className="min-w-0 rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="break-words text-2xl font-black">{t.faq}</h2><details className="group mt-5 min-w-0 border-b pb-4"><summary className="cursor-pointer break-words list-none font-bold">{t.q1}</summary><p className="mt-2 break-words text-sm leading-6 text-slate-600">{t.a1}</p></details><details className="group min-w-0 border-b py-4"><summary className="cursor-pointer break-words list-none font-bold">{t.q2}</summary><p className="mt-2 break-words text-sm leading-6 text-slate-600">{t.a2}</p></details><details className="group min-w-0 border-b py-4"><summary className="cursor-pointer break-words list-none font-bold">{faqLabels[language].question}</summary><p className="mt-2 break-words text-sm leading-6 text-slate-600">{faqLabels[language].answer}</p></details><details className="group min-w-0 py-4"><summary className="cursor-pointer break-words list-none font-bold">{countryName(country,language)} · {t.assumptions}</summary><p className="mt-2 break-words text-sm leading-6 text-slate-600">{specificFaq}</p></details></article></div></section>
  </main><footer className="mt-8 border-t bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-slate-500 lg:px-8"><div className="flex flex-col gap-2 sm:flex-row sm:justify-between"><b className="text-slate-900">{t.brand}</b><span>{t.estimate} · © 2026</span></div><nav className="flex flex-wrap gap-x-5 gap-y-2">{(["about","methodology","sources"] as AuthorityKind[]).map(kind=><a key={kind} className="font-semibold hover:text-blue-700" href={authorityPath(language,kind)}>{authorityLabels[language][kind]}</a>)}{(["privacy","cookies","legal","contact"] as LegalKind[]).map(kind=><a key={kind} className="font-semibold hover:text-blue-700" href={legalPath(language,kind)}>{legalNavLabels[language][kind]}</a>)}</nav></div></footer>
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-2xl bg-white/[.07] p-3.5 sm:p-4"><span className="block break-words text-xs text-slate-300">{label}</span><b className="mt-1 block break-words text-base sm:text-lg">{value}</b></div>}
function Row({label,value,strong}:{label:string;value:string;strong?:boolean}){return <div className={`flex min-w-0 justify-between gap-3 py-2 text-sm ${strong?"text-base font-black":"text-slate-300"}`}><span className="min-w-0 break-words">{label}</span><span className="shrink-0 text-right font-bold text-white">{value}</span></div>}

function PrecisionFields({country,t,value,update}:{country:Country;t:UiText;value:PrecisionOptions;update:<K extends keyof PrecisionOptions>(key:K,value:PrecisionOptions[K])=>void}){
 const input="mt-1 h-11 w-full rounded-lg border border-blue-100 bg-white px-3 font-semibold outline-none focus:ring-4 focus:ring-blue-100";
 return <div className="min-w-0 max-w-full rounded-xl bg-blue-50 p-4 text-sm"><p className="mb-4 text-slate-600">{t.assumptions}</p><div className="grid min-w-0 grid-cols-1 gap-4 sm:grid-cols-2">
  <label className="font-semibold">{t.age}<input className={input} type="number" min="16" max="100" value={value.age??30} onChange={e=>update("age",Number(e.target.value)||30)}/></label>
  <label className="font-semibold">{t.children}<input className={input} type="number" min="0" max="10" value={value.children??0} onChange={e=>update("children",Math.max(0,Number(e.target.value)||0))}/></label>
  <label className="font-semibold">{t.marital}<select className={input} value={value.marital} onChange={e=>update("marital",e.target.value as PrecisionOptions["marital"])}><option value="single">{t.single}</option><option value="married">{t.married}</option></select></label>
  {country.id==="germany"&&<>
   <label className="font-semibold">{t.taxClass}<select className={input} value={value.taxClass} onChange={e=>update("taxClass",e.target.value as PrecisionOptions["taxClass"])}><option value="1">I</option><option value="3">III</option><option value="4">IV</option><option value="5">V</option></select></label>
   <label className="font-semibold">{t.stateGroup}<select className={input} value={value.germanState} onChange={e=>update("germanState",e.target.value as PrecisionOptions["germanState"])}><option value="standard">{t.average} (9%)</option><option value="bavaria-bw">Bayern / Baden-Württemberg (8%)</option></select></label>
   <label className="font-semibold">{t.health}<select className={input} value={value.health} onChange={e=>update("health",e.target.value as PrecisionOptions["health"])}><option value="public">{t.publicHealth}</option><option value="private">{t.privateHealth}</option></select></label>
   <label className="flex items-center justify-between gap-3 rounded-lg border border-blue-100 bg-white px-3 font-semibold sm:mt-6 sm:h-11">{t.church}<input type="checkbox" checked={value.church??false} onChange={e=>update("church",e.target.checked)} className="size-5 accent-blue-600"/></label>
  </>}
  {country.id==="spain"&&<>
   <label className="font-semibold">{t.region}<select className={input} value={value.spainRegion} onChange={e=>update("spainRegion",e.target.value as PrecisionOptions["spainRegion"])}><option value="average">{t.average}</option><option value="low">{t.lower}</option><option value="high">{t.higher}</option></select></label>
   <label className="font-semibold">{t.contract}<select className={input} value={value.contract} onChange={e=>update("contract",e.target.value as PrecisionOptions["contract"])}><option value="permanent">{t.permanent}</option><option value="temporary">{t.temporary}</option></select></label>
  </>}
  {country.id==="united-states"&&<>
   <label className="font-semibold">{t.filing}<select className={input} value={value.filingStatus} onChange={e=>update("filingStatus",e.target.value as PrecisionOptions["filingStatus"])}><option value="single">{t.single}</option><option value="joint">{t.joint}</option><option value="head">{t.head}</option></select></label>
   <label className="font-semibold">{t.stateTax}<select className={input} value={value.stateRate} onChange={e=>update("stateRate",Number(e.target.value))}><option value="0">0%</option><option value="0.03">3%</option><option value="0.05">5%</option><option value="0.08">8%</option><option value="0.1">10%</option></select></label>
  </>}
  {country.id==="switzerland"&&<label className="font-semibold">{t.canton}<select className={input} value={value.canton} onChange={e=>update("canton",e.target.value as PrecisionOptions["canton"])}><option value="average">{t.average}</option><option value="low">{t.lower}</option><option value="high">{t.higher}</option></select></label>}
  {country.id==="canada"&&<label className="font-semibold">{t.province}<select className={input} value={value.province} onChange={e=>update("province",e.target.value as PrecisionOptions["province"])}><option value="ontario">Ontario</option><option value="quebec">Québec</option><option value="alberta">Alberta</option><option value="bc">British Columbia</option></select></label>}
 </div></div>
}
