"use client";

import { useEffect, useMemo, useState } from "react";
import { Calculator, ChevronDown, Globe2, Search, ShieldCheck, Sparkles } from "lucide-react";
import { countries, englishPath, spanishPath, type Country } from "@/lib/countries";
import { calculate } from "@/lib/tax-engine";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";

const text = {
 en:{brand:"ClearSalary",tag:"International salary calculator",title:"See what you actually take home.",sub:"Country-specific tax estimates, explained clearly.",country:"Country",gross:"Gross salary",monthly:"Monthly",annual:"Annual",hours:"Weekly hours (optional)",net:"Estimated net salary",annualNet:"Annual net",hour:"Net / hour",deductions:"Total deductions",keep:"You keep",breakdown:"Your salary breakdown",precise:"Get a more precise result",taxYear:"Tax year",updated:"Last checked",min:"Minimum wage check",below:"This gross hourly rate is below the legal minimum wage.",above:"This gross hourly rate is at or above the legal minimum wage.",method:"Sources & methodology",how:"How the estimate works",copy:"A transparent estimate based on the selected country’s progressive tax brackets, personal allowance and employee social contributions. It is not tax advice.",examples:"Popular salary examples",faq:"Frequently asked questions",q1:"Is this result exact?",a1:"It is a practical estimate. Your final payslip may change with region, family situation, benefits, deductions and employer payroll rules.",q2:"Why is there one result?",a2:"We apply a documented default profile for each country, then let you refine the inputs without showing an unhelpful range.",ad:"Advertisement space",search:"Search countries"},
 es:{brand:"ClearSalary",tag:"Calculadora internacional de salarios",title:"Descubre cuánto dinero te queda realmente.",sub:"Estimaciones fiscales por país, explicadas con claridad.",country:"País",gross:"Salario bruto",monthly:"Mensual",annual:"Anual",hours:"Horas semanales (opcional)",net:"Salario neto estimado",annualNet:"Neto anual",hour:"Neto / hora",deductions:"Deducciones totales",keep:"Te queda",breakdown:"Desglose de tu salario",precise:"Obtener un resultado más preciso",taxYear:"Año fiscal",updated:"Última revisión",min:"Comprobación del salario mínimo",below:"El salario bruto por hora está por debajo del salario mínimo legal.",above:"El salario bruto por hora es igual o superior al salario mínimo legal.",method:"Fuentes y metodología",how:"Cómo funciona la estimación",copy:"Una estimación transparente basada en tramos fiscales, mínimo personal y cotizaciones del trabajador del país seleccionado. No es asesoramiento fiscal.",examples:"Ejemplos de salarios",faq:"Preguntas frecuentes",q1:"¿El resultado es exacto?",a1:"Es una estimación práctica. La nómina final puede variar según región, situación familiar, beneficios, deducciones y reglas de nómina.",q2:"¿Por qué se muestra un único resultado?",a2:"Aplicamos un perfil predeterminado documentado para cada país y permitimos afinarlo sin mostrar un intervalo poco útil.",ad:"Espacio publicitario",search:"Buscar países"}
};

function money(value:number,c:Country,language:"en"|"es",digits=0){return new Intl.NumberFormat(language==="es"?"es-ES":"en-US",{style:"currency",currency:c.currency,maximumFractionDigits:digits}).format(value)}

export function SalaryCalculator({country,language}:{country:Country;language:"en"|"es"}){
 const t=text[language];
 const [salary,setSalary]=useState(3200); const [period,setPeriod]=useState<"monthly"|"annual">("monthly"); const [hours,setHours]=useState(40); const [more,setMore]=useState(false); const [church,setChurch]=useState(false); const [usState,setUsState]=useState("none"); const [query,setQuery]=useState("");
 const result=useMemo(()=>calculate(country,salary,period,hours,{church,state:usState}),[country,salary,period,hours,church,usState]);
 const grossHourly=(period==="monthly"?salary*12:salary)/(Math.max(hours,1)*52);
 const minHourly=country.minimum ? country.minimumPeriod==="hour"?country.minimum:(country.minimum*12)/(40*52):undefined;
 const filtered=countries.filter(c=>(language==="es"?c.es:c.en).toLowerCase().includes(query.toLowerCase()));
 const navigate=(id:string)=>{const c=countries.find(x=>x.id===id)!; window.location.href=language==="es"?spanishPath(c):englishPath(c)};
 const examples=[2000,3200,5000].map(v=>({v,r:calculate(country,v,"monthly",40)}));
 useEffect(()=>{document.documentElement.lang=language},[language]);
 return <div className="min-h-screen bg-[#f6f8fc] text-[#111827]">
  <header className="sticky top-0 z-40 border-b border-slate-200/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#2155f5] text-white shadow-lg shadow-blue-200"><Calculator className="size-5"/></span><span><b className="block text-lg leading-none tracking-tight">{t.brand}</b><small className="text-xs text-slate-500">{t.tag}</small></span></a><div className="flex items-center gap-2"><span className="hidden rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700 sm:inline-flex"><ShieldCheck className="mr-1 size-3.5"/>2026 data</span><a className="rounded-xl border bg-white px-3 py-2 text-sm font-semibold shadow-sm" href={language==="es"?englishPath(country):spanishPath(country)}>{language==="es"?"EN":"ES"}</a></div></div></header>
  <main>
   <section className="mx-auto max-w-7xl px-5 pb-12 pt-10 lg:px-8 lg:pt-16"><div className="mb-9 max-w-3xl"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700"><Sparkles className="size-3.5"/>{country.flag} {language==="es"?country.es:country.en} · 2026</div><h1 className="text-balance text-4xl font-black tracking-[-.04em] sm:text-6xl">{t.title}</h1><p className="mt-4 text-lg text-slate-600">{t.sub}</p></div>
   <div className="grid items-start gap-6 lg:grid-cols-[1.02fr_.98fr]">
    <div className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[0_24px_70px_rgba(39,54,89,.10)] sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="mb-2 block text-sm font-bold">{t.country}</span><Select value={country.id} onValueChange={navigate}><SelectTrigger className="h-14 w-full rounded-xl border-slate-200 bg-slate-50 px-4 text-base"><SelectValue/></SelectTrigger><SelectContent>{countries.map(c=><SelectItem key={c.id} value={c.id}>{c.flag} {language==="es"?c.es:c.en}</SelectItem>)}</SelectContent></Select></label>
    <label className="block sm:col-span-2"><span className="mb-2 block text-sm font-bold">{t.gross}</span><div className="flex h-16 overflow-hidden rounded-xl border border-slate-200 bg-slate-50 focus-within:ring-4 focus-within:ring-blue-100"><span className="grid w-14 place-items-center border-r text-lg font-black text-slate-500">{country.symbol}</span><input aria-label={t.gross} className="min-w-0 flex-1 bg-transparent px-4 text-2xl font-black outline-none" inputMode="decimal" value={salary} onChange={e=>setSalary(Number(e.target.value)||0)}/></div></label>
    <div className="sm:col-span-2 grid grid-cols-2 rounded-xl bg-slate-100 p-1"><button onClick={()=>setPeriod("monthly")} className={`rounded-lg py-3 text-sm font-bold transition ${period==="monthly"?"bg-white text-blue-700 shadow-sm":"text-slate-500"}`}>{t.monthly}</button><button onClick={()=>setPeriod("annual")} className={`rounded-lg py-3 text-sm font-bold transition ${period==="annual"?"bg-white text-blue-700 shadow-sm":"text-slate-500"}`}>{t.annual}</button></div>
    <label className="block sm:col-span-2"><span className="mb-2 block text-sm font-bold">{t.hours}</span><input aria-label={t.hours} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 font-semibold outline-none focus:ring-4 focus:ring-blue-100" type="number" min="1" max="100" value={hours} onChange={e=>setHours(Number(e.target.value)||0)}/></label></div>
    <Collapsible open={more} onOpenChange={setMore} className="mt-5 border-t pt-5"><CollapsibleTrigger className="flex w-full items-center justify-between text-sm font-extrabold text-blue-700">{t.precise}<ChevronDown className={`size-4 transition ${more?"rotate-180":""}`}/></CollapsibleTrigger><CollapsibleContent className="pt-4"><div className="rounded-xl bg-blue-50 p-4 text-sm">{country.id==="germany"?<label className="flex items-center justify-between font-semibold">{language==="es"?"Impuesto eclesiástico":"Church tax"}<input type="checkbox" checked={church} onChange={e=>setChurch(e.target.checked)} className="size-5 accent-blue-600"/></label>:country.id==="united-states"?<label className="block font-semibold">{language==="es"?"Impuesto estatal estimado":"Estimated state tax"}<select value={usState} onChange={e=>setUsState(e.target.value)} className="mt-2 h-11 w-full rounded-lg border bg-white px-3"><option value="none">0% / None</option><option value=".03">3%</option><option value=".05">5%</option><option value=".08">8%</option></select></label>:<p className="text-slate-600">{language==="es"?"El perfil estándar aplica la deducción personal y cotizaciones habituales de un empleado sin circunstancias especiales.":"The standard profile applies the usual personal allowance and employee contributions without special circumstances."}</p>}</div></CollapsibleContent></Collapsible>
    </div>
    <div className="overflow-hidden rounded-[28px] bg-[#101c3b] text-white shadow-[0_26px_80px_rgba(18,31,67,.28)]"><div className="p-6 sm:p-8"><p className="text-sm font-semibold text-blue-200">{t.net}</p><p className="mt-1 text-5xl font-black tracking-[-.05em] sm:text-6xl">{money(result.net,country,language)}</p><p className="mt-2 text-sm text-slate-300">/{period==="monthly"?t.monthly.toLowerCase():t.annual.toLowerCase()}</p><div className="mt-7 grid grid-cols-2 gap-3"><Metric label={t.annualNet} value={money(result.annualNet,country,language)}/><Metric label={t.hour} value={result.hourly?money(result.hourly,country,language,2):"—"}/><Metric label={t.deductions} value={money(result.deductions,country,language)}/><Metric label={t.keep} value={`${result.keep.toFixed(1)}%`}/></div><div className="mt-7"><div className="mb-2 flex justify-between text-xs font-bold"><span>Net</span><span>Deductions</span></div><div className="flex h-3 overflow-hidden rounded-full bg-white/10"><span className="bg-[#4f7cff]" style={{width:`${result.keep}%`}}/><span className="flex-1 bg-[#ffba52]"/></div></div></div><div className="border-t border-white/10 bg-white/[.04] p-6 sm:p-8"><h2 className="mb-4 font-black">{t.breakdown}</h2><Row label={t.gross} value={money(salary,country,language)}/>{result.breakdown.map(x=><Row key={x.label} label={`− ${language==="es"?x.es:x.label}`} value={money(x.amount,country,language)}/>) }<div className="mt-3 border-t border-white/10 pt-3"><Row label={`= ${t.net}`} value={money(result.net,country,language)} strong/></div></div></div>
   </div></section>
   <section className="mx-auto max-w-7xl px-5 pb-10 lg:px-8"><div className="rounded-2xl border border-dashed border-slate-300 bg-white py-5 text-center text-xs font-bold uppercase tracking-[.18em] text-slate-400">{t.ad}</div></section>
   <section className="mx-auto grid max-w-7xl gap-6 px-5 py-8 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-4 flex items-center gap-2"><Globe2 className="size-5 text-blue-600"/><h2 className="text-xl font-black">{language==="es"?"Explora por país":"Explore by country"}</h2></div><div className="relative mb-4"><Search className="absolute left-3 top-3.5 size-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} className="h-11 w-full rounded-xl border bg-slate-50 pl-10 pr-3 outline-none focus:ring-4 focus:ring-blue-100"/></div><div className="worldmap relative h-56 overflow-hidden rounded-2xl bg-[#eef4ff]">{countries.map(c=><a title={language==="es"?c.es:c.en} aria-label={language==="es"?c.es:c.en} key={c.id} href={language==="es"?spanishPath(c):englishPath(c)} className={`absolute grid size-5 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-white bg-blue-600 shadow transition hover:z-10 hover:scale-150 ${c.id===country.id?"ring-4 ring-amber-300":""}`} style={{left:`${c.x}%`,top:`${c.y}%`}}><span className="sr-only">{c.en}</span></a>)}</div><div className="mt-4 grid max-h-52 grid-cols-2 gap-1 overflow-auto pr-1 text-sm">{filtered.map(c=><a className={`rounded-lg px-3 py-2 font-semibold hover:bg-blue-50 ${c.id===country.id?"bg-blue-50 text-blue-700":""}`} key={c.id} href={language==="es"?spanishPath(c):englishPath(c)}>{c.flag} {language==="es"?c.es:c.en}</a>)}</div></div>
   <div className="space-y-6"><article className="rounded-3xl border bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">{t.min}</p><h2 className="mt-2 text-2xl font-black">{country.minimum?`${money(country.minimum,country,language,2)} / ${country.minimumPeriod==="hour"?(language==="es"?"hora":"hour"):(language==="es"?"mes":"month")}`:(language==="es"?"Sin salario mínimo nacional":"No national minimum wage")}</h2>{minHourly&&hours>0?<p className={`mt-3 rounded-xl p-3 text-sm font-semibold ${grossHourly<minHourly?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{grossHourly<minHourly?t.below:t.above}</p>:<p className="mt-3 text-sm text-slate-600">{country.note}</p>}</article>
   <article className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">{t.examples}</h2><div className="mt-4 divide-y">{examples.map(x=><div key={x.v} className="flex justify-between py-3 text-sm"><span>{money(x.v,country,language)} gross</span><b>{money(x.r.net,country,language)} net</b></div>)}</div></article></div></section>
   <section className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">{t.how}</h2><p className="mt-3 leading-7 text-slate-600">{t.copy}</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-50 p-4"><span className="block text-slate-500">{t.taxYear}</span><b>2026</b></div><div className="rounded-xl bg-slate-50 p-4"><span className="block text-slate-500">{t.updated}</span><b>29 Sep 2026</b></div></div><a className="mt-5 inline-flex font-bold text-blue-700 underline decoration-blue-200 underline-offset-4" href={country.sourceUrl} target="_blank" rel="noreferrer">{t.method}: {country.source}</a></article><article className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">{t.faq}</h2><details className="group mt-5 border-b pb-4"><summary className="cursor-pointer list-none font-bold">{t.q1}</summary><p className="mt-2 text-sm leading-6 text-slate-600">{t.a1}</p></details><details className="group py-4"><summary className="cursor-pointer list-none font-bold">{t.q2}</summary><p className="mt-2 text-sm leading-6 text-slate-600">{t.a2}</p></details></article></div></section>
  </main><footer className="mt-8 border-t bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:justify-between lg:px-8"><b className="text-slate-900">ClearSalary</b><span>Estimates for information only · © 2026</span></div></footer>
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white/[.07] p-4"><span className="block text-xs text-slate-300">{label}</span><b className="mt-1 block text-lg">{value}</b></div>}
function Row({label,value,strong}:{label:string;value:string;strong?:boolean}){return <div className={`flex justify-between gap-4 py-2 text-sm ${strong?"text-base font-black":"text-slate-300"}`}><span>{label}</span><span className="font-bold text-white">{value}</span></div>}
