import type { Metadata } from "next";
import { languageAlternates, LAST_UPDATED, locales } from "./seo";
import type { Locale } from "./i18n";

export type AuthorityKind = "about" | "methodology" | "sources";
type LocalizedPage = { title: string; description: string; eyebrow: string; intro: string; sections: { heading: string; paragraphs: string[] }[] };

export const authoritySlugs: Record<Locale, Record<AuthorityKind, string>> = {
  en: { about: "about", methodology: "methodology", sources: "sources-data-updates" },
  es: { about: "sobre-nosotros", methodology: "metodologia", sources: "fuentes-y-actualizaciones" },
  de: { about: "ueber-uns", methodology: "methodik", sources: "quellen-und-datenupdates" },
  fr: { about: "a-propos", methodology: "methodologie", sources: "sources-et-mises-a-jour" },
};

export const authorityLabels: Record<Locale, Record<AuthorityKind, string>> = {
  en: { about: "About", methodology: "Methodology", sources: "Sources & updates" },
  es: { about: "Sobre nosotros", methodology: "Metodología", sources: "Fuentes y actualizaciones" },
  de: { about: "Über uns", methodology: "Methodik", sources: "Quellen & Updates" },
  fr: { about: "À propos", methodology: "Méthodologie", sources: "Sources et mises à jour" },
};

export const authorityPath = (locale: Locale, kind: AuthorityKind) => `${locale === "en" ? "" : `/${locale}`}/${authoritySlugs[locale][kind]}`;
export const authorityKindFromSlug = (locale: Locale, slug: string) => Object.entries(authoritySlugs[locale]).find(([, value]) => value === slug)?.[0] as AuthorityKind | undefined;

const content: Record<AuthorityKind, Record<Locale, LocalizedPage>> = {
  about: {
    en:{title:"About Net Salary Map",description:"Who maintains Net Salary Map and why its international salary calculators are built around clarity, transparency and official sources.",eyebrow:"Independent salary research",intro:"Net Salary Map is an independent project maintained by Héctor Fàbrega Roig to make international gross-to-net salary comparisons faster and easier to understand.",sections:[{heading:"What we publish",paragraphs:["We build country-specific salary calculators, minimum-wage checks and explanatory guides. The project currently covers 25 countries in English, Spanish, German and French.","Each language version uses the same fiscal engine. Translations and localized URLs change how the information is presented, never the underlying tax calculation."]},{heading:"Editorial principles",paragraphs:["We prefer tax authorities, finance ministries, social-security bodies and other government sources. We identify assumptions and approximation limits instead of presenting an estimate as a payslip.","The service is free to use and may be supported by advertising. Advertising does not change calculator results or source selection."]},{heading:"Important limitation",paragraphs:["Results are informational estimates, not tax, financial, legal or payroll advice. A real payslip can differ because of residence, benefits, deductions, payroll timing, collective agreements and individual circumstances."]}]},
    es:{title:"Sobre Net Salary Map",description:"Quién mantiene Net Salary Map y cómo construimos calculadoras salariales internacionales transparentes y basadas en fuentes oficiales.",eyebrow:"Investigación salarial independiente",intro:"Net Salary Map es un proyecto independiente mantenido por Héctor Fàbrega Roig para hacer más rápidas y comprensibles las comparaciones internacionales de salario bruto a neto.",sections:[{heading:"Qué publicamos",paragraphs:["Creamos calculadoras salariales por país, comprobaciones de salario mínimo y guías explicativas. El proyecto cubre actualmente 25 países en inglés, español, alemán y francés.","Cada idioma utiliza el mismo motor fiscal. Las traducciones y URLs localizadas cambian la presentación, nunca el cálculo tributario subyacente."]},{heading:"Principios editoriales",paragraphs:["Priorizamos agencias tributarias, ministerios de finanzas, seguridad social y otras fuentes públicas. Indicamos supuestos y límites en lugar de presentar una estimación como si fuera una nómina.","El servicio es gratuito y puede financiarse con publicidad. La publicidad no modifica los resultados ni la selección de fuentes."]},{heading:"Limitación importante",paragraphs:["Los resultados son estimaciones informativas y no constituyen asesoramiento fiscal, financiero, jurídico o laboral. Una nómina real puede variar por residencia, beneficios, deducciones, calendario de pago, convenio y circunstancias personales."]}]},
    de:{title:"Über Net Salary Map",description:"Wer Net Salary Map betreibt und wie transparente internationale Gehaltsrechner mit offiziellen Quellen entstehen.",eyebrow:"Unabhängige Gehaltsrecherche",intro:"Net Salary Map ist ein unabhängiges Projekt von Héctor Fàbrega Roig. Es macht internationale Brutto-Netto-Vergleiche schneller und verständlicher.",sections:[{heading:"Was wir veröffentlichen",paragraphs:["Wir entwickeln länderspezifische Gehaltsrechner, Mindestlohnprüfungen und erklärende Ratgeber. Derzeit deckt das Projekt 25 Länder auf Englisch, Spanisch, Deutsch und Französisch ab.","Alle Sprachversionen verwenden denselben Steuermotor. Übersetzungen und lokalisierte URLs verändern die Darstellung, nicht die Berechnung."]},{heading:"Redaktionelle Grundsätze",paragraphs:["Wir bevorzugen Finanzbehörden, Ministerien, Sozialversicherungen und andere staatliche Quellen. Annahmen und Grenzen werden offengelegt, statt eine Schätzung als Lohnabrechnung darzustellen.","Der Dienst ist kostenlos und kann durch Werbung finanziert werden. Werbung beeinflusst weder Ergebnisse noch Quellenwahl."]},{heading:"Wichtiger Hinweis",paragraphs:["Die Ergebnisse dienen nur der Information und sind keine Steuer-, Finanz-, Rechts- oder Lohnberatung. Reale Abrechnungen können wegen Wohnort, Leistungen, Abzügen, Tarifverträgen und persönlichen Umständen abweichen."]}]},
    fr:{title:"À propos de Net Salary Map",description:"Qui maintient Net Salary Map et comment nous construisons des calculateurs de salaire internationaux transparents à partir de sources officielles.",eyebrow:"Recherche salariale indépendante",intro:"Net Salary Map est un projet indépendant maintenu par Héctor Fàbrega Roig afin de rendre les comparaisons internationales brut-net plus rapides et compréhensibles.",sections:[{heading:"Ce que nous publions",paragraphs:["Nous créons des calculateurs par pays, des contrôles du salaire minimum et des guides explicatifs. Le projet couvre actuellement 25 pays en anglais, espagnol, allemand et français.","Chaque langue utilise le même moteur fiscal. Les traductions et URL localisées modifient la présentation, jamais le calcul sous-jacent."]},{heading:"Principes éditoriaux",paragraphs:["Nous privilégions administrations fiscales, ministères, sécurité sociale et autres sources publiques. Nous exposons hypothèses et limites au lieu de présenter une estimation comme une fiche de paie.","Le service est gratuit et peut être financé par la publicité. Celle-ci ne modifie ni les résultats ni le choix des sources."]},{heading:"Limite importante",paragraphs:["Les résultats sont informatifs et ne constituent pas un conseil fiscal, financier, juridique ou de paie. Une fiche réelle peut varier selon résidence, avantages, déductions, convention et situation personnelle."]}]},
  },
  methodology: {
    en:{title:"Salary Tax Calculation Methodology",description:"How Net Salary Map turns gross pay into one documented net salary estimate for each country.",eyebrow:"Transparent calculations",intro:"Each country has one independent fiscal configuration and, where needed, dedicated calculation code. The interface always returns one estimate from a documented default profile.",sections:[{heading:"Calculation sequence",paragraphs:["Gross monthly pay is annualised, country-specific employee contributions are calculated with their thresholds and caps, taxable income is derived, and progressive tax bands, allowances and credits are applied. The result is then converted back to the selected period.","Examples shown on country and guide pages call the same calculation function as the interactive calculator."]},{heading:"Country-specific engines",paragraphs:["Germany, Spain, France, the United Kingdom, Ireland, the Netherlands, the United States and Canada have dedicated logic for important rules such as tax classes, personal allowances, filing status, credits, regions or provinces. Other countries use their own configured bands, allowances, contribution categories, caps and national assumptions.","We never apply one flat deduction percentage to every country. Simplified areas are identified in the country explanation."]},{heading:"Default profile and precision",paragraphs:["The simple result uses a resident employee with the most common single-taxpayer profile, no unusual deductions and an average region where regional tax exists. The optional precision panel changes the variables supported by that country.","Employer costs, voluntary pension plans, benefits in kind and exceptional deductions are normally outside scope unless explicitly stated."]},{heading:"Rounding and limitations",paragraphs:["Calculations are annualised and rounded for display. Payroll tables can round each pay period differently, so small differences are normal. Legislative changes may also take effect during a tax year.","This methodology produces a comparable estimate, not an official assessment or professional advice."]}]},
    es:{title:"Metodología de cálculo fiscal del salario",description:"Cómo convierte Net Salary Map el salario bruto en una única estimación documentada de salario neto para cada país.",eyebrow:"Cálculos transparentes",intro:"Cada país tiene una configuración fiscal independiente y, cuando hace falta, código de cálculo específico. La interfaz devuelve siempre una estimación única a partir de un perfil predeterminado documentado.",sections:[{heading:"Secuencia del cálculo",paragraphs:["El salario mensual se anualiza; se calculan las cotizaciones del trabajador con sus umbrales y topes; se obtiene la base imponible; y se aplican tramos progresivos, mínimos y créditos. Después se convierte el resultado al periodo seleccionado.","Los ejemplos de páginas de país y guías llaman a la misma función que la calculadora interactiva."]},{heading:"Motores específicos por país",paragraphs:["Alemania, España, Francia, Reino Unido, Irlanda, Países Bajos, Estados Unidos y Canadá tienen lógica dedicada para clases fiscales, mínimos, estado de declaración, créditos, regiones o provincias. Los demás países usan sus propios tramos, mínimos, categorías de cotización, topes y supuestos.","Nunca aplicamos un único porcentaje fijo a todos los países. Las simplificaciones se explican en la página correspondiente."]},{heading:"Perfil inicial y precisión",paragraphs:["El resultado sencillo supone un trabajador residente, el perfil individual más habitual, sin deducciones extraordinarias y una región media cuando existen diferencias territoriales. El panel avanzado modifica las variables disponibles para ese país.","Los costes empresariales, planes voluntarios, retribución en especie y deducciones excepcionales quedan normalmente fuera salvo indicación expresa."]},{heading:"Redondeo y límites",paragraphs:["Los cálculos se anualizan y se redondean al mostrarlos. Las tablas de nómina pueden redondear cada periodo de otra forma, por lo que son normales pequeñas diferencias.","La metodología ofrece una estimación comparable, no una liquidación oficial ni asesoramiento profesional."]}]},
    de:{title:"Methodik der Gehalts- und Steuerberechnung",description:"Wie Net Salary Map aus dem Bruttogehalt für jedes Land eine dokumentierte Netto-Schätzung berechnet.",eyebrow:"Transparente Berechnungen",intro:"Jedes Land besitzt eine eigene Steuerkonfiguration und bei Bedarf speziellen Berechnungscode. Die Oberfläche liefert anhand eines dokumentierten Standardprofils stets einen Schätzwert.",sections:[{heading:"Rechenfolge",paragraphs:["Das Monatsbrutto wird annualisiert. Danach werden Arbeitnehmerbeiträge mit Grenzen und Höchstbeträgen, das steuerpflichtige Einkommen sowie progressive Stufen, Freibeträge und Gutschriften berechnet. Anschließend wird das Ergebnis in den gewählten Zeitraum zurückgerechnet.","Beispiele auf Länder- und Ratgeberseiten nutzen dieselbe Funktion wie der interaktive Rechner."]},{heading:"Länderspezifische Motoren",paragraphs:["Deutschland, Spanien, Frankreich, das Vereinigte Königreich, Irland, die Niederlande, die USA und Kanada besitzen Speziallogik für Steuerklassen, Freibeträge, Veranlagung, Gutschriften, Regionen oder Provinzen. Andere Länder verwenden eigene Stufen, Beiträge, Grenzen und Annahmen.","Wir wenden niemals einen einheitlichen Pauschalabzug auf alle Länder an. Vereinfachungen stehen in der Ländererklärung."]},{heading:"Standardprofil und Genauigkeit",paragraphs:["Das einfache Ergebnis nimmt einen ansässigen Arbeitnehmer mit üblichem Einzelprofil, ohne ungewöhnliche Abzüge und mit einer Durchschnittsregion an. Das Präzisionsfeld ändert die für das Land unterstützten Variablen.","Arbeitgeberkosten, freiwillige Vorsorge, Sachbezüge und außergewöhnliche Abzüge sind normalerweise nicht enthalten."]},{heading:"Rundung und Grenzen",paragraphs:["Die Rechnung erfolgt jährlich und wird für die Anzeige gerundet. Lohnabrechnungstabellen können je Zahlungsperiode anders runden, weshalb kleine Abweichungen normal sind.","Die Methodik liefert einen Vergleichswert, keinen offiziellen Steuerbescheid und keine Beratung."]}]},
    fr:{title:"Méthodologie du calcul fiscal du salaire",description:"Comment Net Salary Map transforme le brut en une estimation nette unique et documentée pour chaque pays.",eyebrow:"Calculs transparents",intro:"Chaque pays possède une configuration fiscale indépendante et, si nécessaire, un code de calcul dédié. L’interface renvoie toujours une estimation issue d’un profil par défaut documenté.",sections:[{heading:"Séquence du calcul",paragraphs:["Le brut mensuel est annualisé; les cotisations salariales sont calculées avec leurs seuils et plafonds; le revenu imposable est déterminé; puis barèmes progressifs, abattements et crédits sont appliqués. Le résultat revient ensuite à la période choisie.","Les exemples des pages pays et guides appellent exactement la même fonction que le calculateur interactif."]},{heading:"Moteurs propres à chaque pays",paragraphs:["Allemagne, Espagne, France, Royaume-Uni, Irlande, Pays-Bas, États-Unis et Canada disposent d’une logique dédiée aux classes, abattements, statut, crédits, régions ou provinces. Les autres pays ont leurs propres tranches, cotisations, plafonds et hypothèses.","Nous n’appliquons jamais un taux forfaitaire unique à tous les pays. Les simplifications sont signalées sur la page concernée."]},{heading:"Profil par défaut et précision",paragraphs:["Le résultat simple suppose un salarié résident au profil individuel courant, sans déduction inhabituelle et dans une région moyenne lorsque la fiscalité varie. Le panneau de précision modifie les variables prises en charge.","Coûts employeur, retraite volontaire, avantages en nature et déductions exceptionnelles sont généralement hors périmètre."]},{heading:"Arrondis et limites",paragraphs:["Les calculs sont annualisés puis arrondis à l’affichage. Les logiciels de paie peuvent arrondir chaque période autrement, donc de petits écarts sont normaux.","Cette méthode fournit une estimation comparable, pas une évaluation officielle ni un conseil professionnel."]}]},
  },
  sources: {
    en:{title:"Sources and Data Updates",description:"Official data sources, review process and update policy for Net Salary Map salary calculators.",eyebrow:"Data transparency",intro:"Every country page names its tax year, review date and source links. This page explains how those inputs are selected, checked and updated.",sections:[{heading:"Source hierarchy",paragraphs:["We prioritise tax authorities, finance ministries, social-security institutions, labour ministries and official legislation. Official payroll calculators and government explanatory pages are used where primary legal text is difficult to operationalise.","Datosmacro may support minimum-wage comparison, but a government or statutory source is preferred whenever available. A national minimum is never invented where none exists."]},{heading:"Review process",paragraphs:["Rates, bands, allowances, contribution ceilings and minimum wages are reviewed when a new tax year begins or a government announces a material change. Each country page displays the last review date.","A source being updated does not always mean payroll software changes immediately. We document transitional or simplified treatment where it materially affects the estimate."]},{heading:"Corrections",paragraphs:["If you find an outdated rate or broken official source, contact linkedlab.info@gmail.com with the country, source and expected correction. We review reproducible reports and update the engine, explanation and date together."]},{heading:"Current data status",paragraphs:[`The current public dataset is marked for tax year 2026 and was last reviewed on ${LAST_UPDATED}. Coverage quality differs by country because some systems publish exact formulas while others depend on local payroll tables.`]}]},
    es:{title:"Fuentes y actualizaciones de datos",description:"Fuentes oficiales, proceso de revisión y política de actualización de las calculadoras de Net Salary Map.",eyebrow:"Transparencia de datos",intro:"Cada página de país muestra año fiscal, fecha de revisión y enlaces de fuentes. Aquí explicamos cómo se seleccionan, comprueban y actualizan esos datos.",sections:[{heading:"Jerarquía de fuentes",paragraphs:["Priorizamos agencias tributarias, ministerios de finanzas, seguridad social, ministerios de trabajo y legislación oficial. Usamos calculadoras oficiales y páginas explicativas cuando el texto legal no se puede convertir directamente en una fórmula.","Datosmacro puede apoyar comparaciones de salario mínimo, pero se prefiere una fuente pública o normativa siempre que exista. Nunca inventamos un mínimo nacional donde no lo hay."]},{heading:"Proceso de revisión",paragraphs:["Revisamos tipos, tramos, mínimos, topes y salarios mínimos al comenzar un ejercicio o ante un cambio gubernamental relevante. Cada página muestra la última fecha de comprobación.","Que una fuente cambie no implica que todas las nóminas cambien inmediatamente. Documentamos periodos transitorios o simplificaciones cuando afectan al resultado."]},{heading:"Correcciones",paragraphs:["Si detectas un tipo desactualizado o una fuente rota, escribe a linkedlab.info@gmail.com indicando país, fuente y corrección esperada. Revisamos los avisos reproducibles y actualizamos a la vez motor, explicación y fecha."]},{heading:"Estado actual",paragraphs:[`El conjunto público está marcado para el ejercicio 2026 y se revisó por última vez el ${LAST_UPDATED}. La precisión varía porque algunos sistemas publican fórmulas exactas y otros dependen de tablas locales de nómina.`]}]},
    de:{title:"Quellen und Datenaktualisierungen",description:"Offizielle Datenquellen, Prüfprozess und Update-Richtlinie der Net Salary Map Gehaltsrechner.",eyebrow:"Datentransparenz",intro:"Jede Länderseite nennt Steuerjahr, Prüfdatum und Quellenlinks. Hier erklären wir Auswahl, Kontrolle und Aktualisierung dieser Daten.",sections:[{heading:"Quellenhierarchie",paragraphs:["Wir priorisieren Finanzbehörden, Ministerien, Sozialversicherungen, Arbeitsministerien und amtliche Gesetze. Offizielle Rechner und Erläuterungen helfen, wenn Gesetzestext nicht direkt als Formel umsetzbar ist.","Datosmacro kann Mindestlohnvergleiche unterstützen; wenn verfügbar, wird eine staatliche oder gesetzliche Quelle bevorzugt. Ohne nationales Minimum erfinden wir keines."]},{heading:"Prüfprozess",paragraphs:["Sätze, Stufen, Freibeträge, Beitragsgrenzen und Mindestlöhne werden zum neuen Steuerjahr oder bei wesentlichen Änderungen geprüft. Jede Länderseite zeigt das letzte Prüfdatum.","Eine neue Quelle ändert Lohnsoftware nicht immer sofort. Übergänge oder Vereinfachungen werden bei relevantem Einfluss dokumentiert."]},{heading:"Korrekturen",paragraphs:["Melde veraltete Sätze oder defekte Quellen mit Land, Quelle und erwarteter Korrektur an linkedlab.info@gmail.com. Nachvollziehbare Meldungen führen zu gemeinsamer Aktualisierung von Motor, Erklärung und Datum."]},{heading:"Aktueller Stand",paragraphs:[`Der öffentliche Datensatz gilt für 2026 und wurde zuletzt am ${LAST_UPDATED} geprüft. Die Genauigkeit variiert, weil manche Systeme exakte Formeln, andere lokale Lohnsteuertabellen veröffentlichen.`]}]},
    fr:{title:"Sources et mises à jour des données",description:"Sources officielles, processus de révision et politique de mise à jour des calculateurs Net Salary Map.",eyebrow:"Transparence des données",intro:"Chaque page pays indique année fiscale, date de contrôle et liens sources. Cette page explique leur sélection, vérification et mise à jour.",sections:[{heading:"Hiérarchie des sources",paragraphs:["Nous privilégions administrations fiscales, ministères, sécurité sociale, ministères du travail et textes officiels. Les simulateurs publics servent lorsque la loi ne se convertit pas directement en formule.","Datosmacro peut compléter la comparaison des minima, mais une source publique ou légale est préférée. Aucun minimum national n’est inventé lorsqu’il n’existe pas."]},{heading:"Processus de révision",paragraphs:["Taux, tranches, abattements, plafonds et salaires minimums sont contrôlés au début d’une année fiscale ou lors d’un changement important. Chaque page affiche la dernière vérification.","Une source modifiée ne change pas toujours immédiatement les logiciels de paie. Les transitions ou simplifications importantes sont documentées."]},{heading:"Corrections",paragraphs:["Pour signaler un taux obsolète ou une source cassée, écrivez à linkedlab.info@gmail.com avec pays, source et correction attendue. Les signalements reproductibles entraînent la mise à jour du moteur, de l’explication et de la date."]},{heading:"État actuel",paragraphs:[`Le jeu public correspond à 2026 et a été révisé le ${LAST_UPDATED}. La précision varie car certains systèmes publient des formules exactes, d’autres des tables locales de paie.`]}]},
  },
};

export const getAuthorityPage = (locale: Locale, kind: AuthorityKind) => content[kind][locale];
export function authorityMetadata(locale: Locale, kind: AuthorityKind): Metadata {
  const page = getAuthorityPage(locale, kind);
  const paths = Object.fromEntries(locales.map((item) => [item, authorityPath(item, kind)])) as Record<Locale, string>;
  return { title: page.title, description: page.description, alternates:{canonical:paths[locale],languages:languageAlternates(paths)},openGraph:{type:"website",locale,url:paths[locale],title:page.title,description:page.description,siteName:"Net Salary Map"} };
}
