import type { Country } from "./countries";
import type { Locale } from "./i18n";

type Localized = Record<Locale,string>;

export const guideLabels: Record<Locale,{
  system:string; rates:string; upTo:string; above:string; contributions:string; rate:string;
  assumptions:string; sources:string; sourceNote:string; specificFaq:string; specificAnswer:string; included:string;
}> = {
  en:{system:"How salary tax works",rates:"Indicative income-tax bands",upTo:"Up to",above:"Above",contributions:"Employee contributions used",rate:"Rate",assumptions:"Default assumptions",sources:"Official sources",sourceNote:"Rates are simplified for an annual employee estimate. Local taxes, benefits, deductions and payroll rounding may change the final payslip.",specificFaq:"What can change this estimate?",specificAnswer:"Residence, family status, age, benefits, regional rules, tax credits and payroll timing can all change the final amount.",included:"Included in tax"},
  es:{system:"Cómo funciona la fiscalidad salarial",rates:"Tramos orientativos del impuesto",upTo:"Hasta",above:"Más de",contributions:"Cotizaciones del trabajador utilizadas",rate:"Tipo",assumptions:"Supuestos predeterminados",sources:"Fuentes oficiales",sourceNote:"Los tipos se simplifican para obtener una estimación anual de un trabajador. Los impuestos locales, beneficios, deducciones y redondeos pueden modificar la nómina final.",specificFaq:"¿Qué puede cambiar esta estimación?",specificAnswer:"La residencia, situación familiar, edad, beneficios, reglas regionales, deducciones y el momento del pago pueden cambiar el importe final.",included:"Incluido en el impuesto"},
  de:{system:"So funktioniert die Gehaltsbesteuerung",rates:"Verwendete Einkommensteuerstufen",upTo:"Bis",above:"Über",contributions:"Berücksichtigte Arbeitnehmerbeiträge",rate:"Satz",assumptions:"Standardannahmen",sources:"Amtliche Quellen",sourceNote:"Die Sätze werden für eine jährliche Arbeitnehmerschätzung vereinfacht. Kommunale Steuern, Leistungen, Abzüge und Rundungen können die Abrechnung verändern.",specificFaq:"Was kann die Schätzung verändern?",specificAnswer:"Wohnort, Familie, Alter, Leistungen, regionale Regeln, Freibeträge und Abrechnungszeitpunkt können den Endbetrag verändern.",included:"In Steuer enthalten"},
  fr:{system:"Fonctionnement de l’imposition salariale",rates:"Tranches indicatives utilisées",upTo:"Jusqu’à",above:"Au-delà de",contributions:"Cotisations salariales retenues",rate:"Taux",assumptions:"Hypothèses par défaut",sources:"Sources officielles",sourceNote:"Les taux sont simplifiés pour une estimation annuelle de salarié. Impôts locaux, avantages, déductions et arrondis peuvent modifier la fiche de paie finale.",specificFaq:"Qu’est-ce qui peut modifier l’estimation ?",specificAnswer:"Résidence, situation familiale, âge, avantages, règles régionales, crédits et calendrier de paie peuvent modifier le montant final.",included:"Inclus dans l’impôt"},
};

export const countryGuides: Record<string,Localized> = {
  germany:{en:"Germany combines progressive income tax with pension, health, unemployment and long-term-care insurance. The default profile is a single employee in tax class I, without church tax and with statutory health insurance.",es:"Alemania combina un impuesto progresivo con cotizaciones de pensión, salud, desempleo y dependencia. El perfil inicial es una persona soltera, clase fiscal I, sin impuesto eclesiástico y con seguro público.",de:"Deutschland kombiniert eine progressive Einkommensteuer mit Renten-, Kranken-, Arbeitslosen- und Pflegeversicherung. Standard ist eine ledige Person in Steuerklasse I ohne Kirchensteuer mit gesetzlicher Krankenversicherung.",fr:"L’Allemagne combine impôt progressif et cotisations retraite, maladie, chômage et dépendance. Le profil par défaut est célibataire, classe fiscale I, sans impôt cultuel et assuré dans le public."},
  spain:{en:"Spain applies national and regional IRPF scales after employee Social Security and personal/family minima. The calculator uses an average regional scale and a permanent contract by default.",es:"España aplica escalas estatales y autonómicas de IRPF después de cotizaciones y mínimos personales y familiares. La calculadora usa por defecto una comunidad de tributación media y contrato indefinido.",de:"Spanien wendet staatliche und regionale IRPF-Tarife nach Sozialbeiträgen sowie persönlichen und familiären Freibeträgen an. Standard ist eine Region mit durchschnittlicher Belastung und ein unbefristeter Vertrag.",fr:"L’Espagne applique des barèmes IRPF nationaux et régionaux après cotisations et minima personnels/familiaux. Le calcul utilise par défaut une région moyenne et un contrat permanent."},
  france:{en:"France combines employee social contributions with progressive household income tax. The estimate applies the standard 10% employment-income deduction and the household quotient.",es:"Francia combina cotizaciones del trabajador con un impuesto familiar progresivo. La estimación aplica la deducción estándar del 10% y el cociente familiar.",de:"Frankreich kombiniert Arbeitnehmerbeiträge mit einer progressiven Haushaltsbesteuerung. Die Schätzung nutzt den pauschalen 10-%-Werbungskostenabzug und den Familienquotienten.",fr:"La France combine cotisations salariales et impôt progressif du foyer. L’estimation applique l’abattement de 10 % et le quotient familial."},
  portugal:{en:"Portugal deducts employee Social Security and a standard employment deduction before applying the progressive IRS schedule. The estimate uses mainland rules and does not model every withholding-table status.",es:"Portugal descuenta la Seguridad Social y la deducción específica del trabajo antes de aplicar el IRS progresivo. La estimación usa reglas del continente y no reproduce todos los estados de retención.",de:"Portugal zieht Sozialversicherung und den pauschalen Arbeitnehmerabzug vor Anwendung des progressiven IRS ab. Verwendet werden Festlandregeln ohne jede Variante der Quellensteuertabellen.",fr:"Le Portugal déduit la sécurité sociale et l’abattement salarié avant le barème progressif de l’IRS. L’estimation suit le continent sans reproduire chaque table de retenue."},
  italy:{en:"Italy applies national IRPEF bands after employee social-security contributions. Regional and municipal surcharges and employment tax credits are approximated, so the result is indicative.",es:"Italia aplica los tramos nacionales del IRPEF tras las cotizaciones. Los recargos regionales y municipales y los créditos laborales se aproximan.",de:"Italien wendet die nationalen IRPEF-Stufen nach Sozialbeiträgen an. Regionale und kommunale Zuschläge sowie Arbeitnehmergutschriften werden angenähert.",fr:"L’Italie applique les tranches nationales IRPEF après cotisations. Les surtaxes régionales et communales et crédits salariés sont approximés."},
  netherlands:{en:"The Netherlands taxes employment in Box 1 and includes national-insurance premiums in the first band. The calculator applies the 2026 general tax credit and employment credit phase-outs.",es:"Países Bajos grava el empleo en la Box 1 e integra los seguros nacionales en el primer tramo. Se aplican las reducciones general y laboral de 2026.",de:"Die Niederlande besteuern Arbeit in Box 1; in der ersten Stufe sind Volksversicherungen enthalten. Die Schätzung berücksichtigt 2026 allgemeine und arbeitsbezogene Gutschriften.",fr:"Les Pays-Bas imposent le travail en Box 1, avec assurances nationales dans la première tranche. Le calcul applique les crédits général et professionnel 2026."},
  belgium:{en:"Belgium combines progressive federal income tax with employee Social Security. The estimate uses the tax-free allowance but simplifies employment expenses and the municipal surcharge.",es:"Bélgica combina impuesto federal progresivo y Seguridad Social. La estimación usa el mínimo exento, simplificando gastos profesionales y recargo municipal.",de:"Belgien kombiniert progressive Bundessteuer und Sozialversicherung. Die Schätzung nutzt den Grundfreibetrag und vereinfacht Berufskosten sowie Gemeindesteuer.",fr:"La Belgique combine impôt fédéral progressif et sécurité sociale. L’estimation utilise la quotité exemptée et simplifie frais professionnels et taxe communale."},
  luxembourg:{en:"Luxembourg uses tax classes, a progressive scale and employee pension, health and dependency contributions. The default is an unmarried taxpayer in class 1.",es:"Luxemburgo utiliza clases fiscales, una escala progresiva y cotizaciones de pensión, salud y dependencia. El perfil inicial es una persona soltera en clase 1.",de:"Luxemburg nutzt Steuerklassen, einen progressiven Tarif sowie Renten-, Kranken- und Pflegebeiträge. Standard ist eine unverheiratete Person in Klasse 1.",fr:"Le Luxembourg utilise classes d’impôt, barème progressif et cotisations retraite, maladie et dépendance. Le défaut est une personne célibataire en classe 1."},
  austria:{en:"Austria applies progressive income-tax bands after employee social insurance. Collective agreements set most wage floors, so no single national minimum is shown.",es:"Austria aplica tramos progresivos después del seguro social. Los convenios fijan la mayoría de salarios mínimos, por lo que no se muestra un mínimo nacional único.",de:"Österreich wendet progressive Steuerstufen nach Sozialversicherung an. Kollektivverträge bestimmen meist die Lohnuntergrenze; daher gibt es keinen einheitlichen gesetzlichen Mindestlohn.",fr:"L’Autriche applique un barème progressif après assurance sociale. Les conventions fixent la plupart des minima, sans minimum national unique."},
  switzerland:{en:"Swiss net pay depends on federal, cantonal and municipal tax plus AHV/IV/EO and unemployment insurance. The default uses an average-canton approximation and excludes private health premiums.",es:"En Suiza el neto depende de impuestos federales, cantonales y municipales, además de AHV/IV/EO y desempleo. Se usa un cantón medio y se excluye el seguro médico privado.",de:"In der Schweiz hängt das Netto von Bundes-, Kantons- und Gemeindesteuern sowie AHV/IV/EO und Arbeitslosenversicherung ab. Standard ist ein Durchschnittskanton; Krankenkassenprämien sind nicht enthalten.",fr:"En Suisse, le net dépend des impôts fédéral, cantonal et communal ainsi que de l’AVS/AI/APG et du chômage. Le défaut utilise un canton moyen et exclut l’assurance maladie privée."},
  "united-kingdom":{en:"The UK estimate uses the Personal Allowance, progressive income tax and employee National Insurance for England, Wales and Northern Ireland. Scotland has separate income-tax bands.",es:"La estimación del Reino Unido usa Personal Allowance, impuesto progresivo y National Insurance para Inglaterra, Gales e Irlanda del Norte. Escocia tiene tramos propios.",de:"Die UK-Schätzung nutzt Personal Allowance, progressive Einkommensteuer und National Insurance für England, Wales und Nordirland. Schottland hat eigene Stufen.",fr:"L’estimation britannique utilise Personal Allowance, impôt progressif et National Insurance pour l’Angleterre, le pays de Galles et l’Irlande du Nord. L’Écosse a son propre barème."},
  ireland:{en:"Ireland combines PAYE income tax, PRSI and the Universal Social Charge. Personal and employee credits are applied to the default estimate.",es:"Irlanda combina PAYE, PRSI y Universal Social Charge. La estimación aplica los créditos personal y del trabajador.",de:"Irland kombiniert PAYE-Einkommensteuer, PRSI und Universal Social Charge. Persönliche und Arbeitnehmergutschriften werden berücksichtigt.",fr:"L’Irlande combine PAYE, PRSI et Universal Social Charge. Les crédits personnel et salarié sont appliqués."},
  denmark:{en:"Denmark deducts the 8% labour-market contribution and then applies municipal and state taxation. The result uses an average municipality and a basic personal allowance.",es:"Dinamarca descuenta la contribución laboral del 8% y aplica impuestos municipales y estatales. El resultado usa un municipio medio y una deducción personal básica.",de:"Dänemark zieht 8 % Arbeitsmarktbeitrag ab und erhebt danach Gemeinde- und Staatssteuer. Die Schätzung nutzt eine Durchschnittsgemeinde und den Grundfreibetrag.",fr:"Le Danemark déduit 8 % de contribution au marché du travail puis applique impôts municipal et national. Le calcul utilise une commune moyenne et l’abattement personnel."},
  sweden:{en:"Sweden mainly taxes salary through municipal income tax, with national tax above the state threshold. The calculator uses an average municipal rate and an employee pension contribution.",es:"Suecia grava principalmente mediante impuesto municipal y añade impuesto estatal por encima del umbral. Se usa un tipo municipal medio y la aportación de pensión.",de:"Schweden besteuert Gehalt vor allem kommunal und erhebt oberhalb der Schwelle Staatssteuer. Verwendet werden ein durchschnittlicher Gemeindesatz und Rentenbeitrag.",fr:"La Suède impose surtout le salaire au niveau communal et ajoute l’impôt national au-dessus du seuil. Le calcul utilise un taux communal moyen et la retraite salariale."},
  norway:{en:"Norway combines ordinary income tax, bracket tax and National Insurance. The configuration blends these layers into progressive effective bands after a basic allowance.",es:"Noruega combina impuesto ordinario, impuesto por tramos y Seguro Nacional. La configuración aproxima estas capas mediante tipos efectivos progresivos tras un mínimo.",de:"Norwegen kombiniert allgemeine Einkommensteuer, Stufensteuer und Sozialversicherung. Die Konfiguration nähert diese Ebenen über progressive Effektivsätze nach Freibetrag an.",fr:"La Norvège combine impôt ordinaire, impôt par tranches et assurance nationale. La configuration rapproche ces couches par des taux effectifs progressifs après abattement."},
  finland:{en:"Finland combines state income tax, municipal tax and employee pension and unemployment contributions. The estimate uses an average municipality.",es:"Finlandia combina impuesto estatal y municipal con cotizaciones de pensión y desempleo. La estimación usa un municipio medio.",de:"Finnland kombiniert staatliche und kommunale Steuer mit Renten- und Arbeitslosenbeiträgen. Die Schätzung nutzt eine Durchschnittsgemeinde.",fr:"La Finlande combine impôts national et municipal avec cotisations retraite et chômage. L’estimation utilise une commune moyenne."},
  poland:{en:"Poland applies a tax-free amount and progressive PIT, plus pension, disability, sickness and health contributions. Special reliefs for young workers are not applied by default.",es:"Polonia aplica un mínimo exento y PIT progresivo, además de pensión, incapacidad, enfermedad y salud. No se aplican por defecto ventajas para jóvenes.",de:"Polen nutzt einen Freibetrag und progressive PIT sowie Renten-, Invaliditäts-, Krankengeld- und Krankenbeiträge. Jugendfreibeträge sind standardmäßig nicht enthalten.",fr:"La Pologne applique abattement et PIT progressif, plus retraite, invalidité, maladie et santé. Les exonérations jeunes ne sont pas appliquées par défaut."},
  "czech-republic":{en:"Czech payroll uses personal income tax plus employee social and health insurance. The estimate includes the basic personal allowance but not every monthly tax credit.",es:"La nómina checa aplica impuesto personal y seguros social y médico. Se incluye la deducción personal básica, no todos los créditos mensuales.",de:"Tschechische Löhne unterliegen Einkommensteuer sowie Sozial- und Krankenversicherung. Der persönliche Grundabzug ist enthalten, nicht jede monatliche Gutschrift.",fr:"La paie tchèque comprend impôt personnel et assurances sociale et maladie. L’abattement personnel de base est inclus, pas tous les crédits mensuels."},
  greece:{en:"Greece applies progressive income tax and employee social insurance. The calculation is an annualised estimate and simplifies tax credits linked to family status.",es:"Grecia aplica impuesto progresivo y seguro social del trabajador. El cálculo anualiza el resultado y simplifica créditos familiares.",de:"Griechenland erhebt progressive Einkommensteuer und Sozialbeiträge. Die Jahresberechnung vereinfacht familienbezogene Gutschriften.",fr:"La Grèce applique impôt progressif et assurance sociale salariale. Le calcul annualisé simplifie les crédits familiaux."},
  hungary:{en:"Hungary uses a flat personal income-tax rate plus employee Social Security. Family tax allowances can materially raise net pay and are approximated through the optional children input.",es:"Hungría usa un impuesto personal único y Seguridad Social. Las ventajas familiares pueden elevar mucho el neto y se aproximan con el campo hijos.",de:"Ungarn nutzt eine einheitliche Einkommensteuer plus Sozialversicherung. Familienfreibeträge können das Netto deutlich erhöhen und werden über Kinder angenähert.",fr:"La Hongrie utilise un impôt personnel forfaitaire et la sécurité sociale. Les avantages familiaux peuvent augmenter fortement le net et sont approximés via le nombre d’enfants."},
  romania:{en:"Romania deducts pension and health contributions before applying the flat income-tax rate. Low-income personal deductions are simplified.",es:"Rumanía descuenta pensión y salud antes de aplicar el tipo único del impuesto. Las deducciones personales de rentas bajas se simplifican.",de:"Rumänien zieht Renten- und Krankenbeiträge vor der einheitlichen Einkommensteuer ab. Persönliche Abzüge bei niedrigen Einkommen werden vereinfacht.",fr:"La Roumanie déduit retraite et santé avant l’impôt forfaitaire. Les déductions personnelles des bas revenus sont simplifiées."},
  croatia:{en:"Croatia combines employee pension contributions with progressive local income-tax rates. The estimate uses representative national bands and a personal allowance.",es:"Croacia combina pensiones del trabajador con tipos locales progresivos. La estimación usa tramos representativos y una deducción personal.",de:"Kroatien kombiniert Arbeitnehmer-Rentenbeiträge mit progressiven lokalen Steuersätzen. Die Schätzung nutzt repräsentative Stufen und einen persönlichen Freibetrag.",fr:"La Croatie combine retraite salariale et taux locaux progressifs. L’estimation utilise des tranches représentatives et un abattement personnel."},
  bulgaria:{en:"Bulgaria applies capped employee social and health contributions and a flat income-tax rate to the remaining taxable salary.",es:"Bulgaria aplica cotizaciones sociales y médicas con tope y un impuesto único sobre el salario restante.",de:"Bulgarien erhebt gedeckelte Sozial- und Krankenbeiträge und danach eine einheitliche Einkommensteuer.",fr:"La Bulgarie applique des cotisations sociales et maladie plafonnées puis un impôt forfaitaire sur le salaire restant."},
  "united-states":{en:"The US estimate applies federal income-tax brackets, the standard deduction, Social Security and Medicare. State and local income tax is zero by default and can be added in the precise options.",es:"La estimación de Estados Unidos aplica tramos federales, deducción estándar, Social Security y Medicare. El impuesto estatal y local es cero por defecto y puede añadirse.",de:"Die US-Schätzung nutzt Bundesstufen, Standard Deduction, Social Security und Medicare. Staats- und Lokalsteuer ist standardmäßig null und kann ergänzt werden.",fr:"L’estimation américaine applique tranches fédérales, déduction standard, Social Security et Medicare. L’impôt d’État/local vaut zéro par défaut et peut être ajouté."},
  canada:{en:"Canada combines federal tax, provincial tax, CPP/QPP and Employment Insurance. Ontario is the default province and can be changed in the precise options.",es:"Canadá combina impuesto federal y provincial, CPP/QPP y Employment Insurance. Ontario es la provincia predeterminada y puede cambiarse.",de:"Kanada kombiniert Bundes- und Provinzsteuer, CPP/QPP und Employment Insurance. Ontario ist Standard und kann geändert werden.",fr:"Le Canada combine impôts fédéral et provincial, RPC/RRQ et assurance-emploi. L’Ontario est la province par défaut et peut être modifié."},
};

const additionalSources: Record<string,{label:string;url:string}[]> = {
  germany:[{label:"Federal Government – minimum wage 2026",url:"https://www.bundesregierung.de/breg-de/leichte-sprache/mindestlohn-steigt-weiter-2393118"}],
  spain:[{label:"BOE – 2026 statutory minimum wage",url:"https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-3815"}],
  portugal:[{label:"Government of Portugal – 2026 changes",url:"https://portugal.gov.pt/gc25/comunicacao/noticias/o-que-muda-em-2026"}],
  netherlands:[{label:"Belastingdienst – 2026 rates and credits",url:"https://www.belastingdienst.nl/wps/wcm/connect/nl/voorlopige-aanslag/content/voorlopige-aanslag-tarieven-en-heffingskortingen"}],
  austria:[{label:"Austrian Finance Ministry – 2026 calculator",url:"https://www.bmf.gv.at/services/berechnungsprogramme.html"}],
  "united-kingdom":[{label:"GOV.UK – minimum wage rates",url:"https://www.gov.uk/national-minimum-wage-rates"}],
  "united-states":[{label:"IRS – tax inflation adjustments",url:"https://www.irs.gov/newsroom/tax-inflation-adjustments"}],
  canada:[{label:"Canada Revenue Agency – payroll deductions",url:"https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll.html"}],
};

export function sourcesFor(country: Country) {
  return [{label:country.source,url:country.sourceUrl},...(additionalSources[country.id]??[])];
}

export function contributionLabel(label:string, locale:Locale) {
  const dictionary:Record<string,Localized> = {
    "Pension":{en:"Pension",es:"Pensión",de:"Rentenversicherung",fr:"Retraite"},
    "Health insurance":{en:"Health insurance",es:"Seguro médico",de:"Krankenversicherung",fr:"Assurance maladie"},
    "Health":{en:"Health",es:"Salud",de:"Krankenversicherung",fr:"Santé"},
    "Unemployment":{en:"Unemployment",es:"Desempleo",de:"Arbeitslosenversicherung",fr:"Chômage"},
    "Long-term care":{en:"Long-term care",es:"Dependencia",de:"Pflegeversicherung",fr:"Dépendance"},
    "Care insurance":{en:"Care insurance",es:"Seguro de dependencia",de:"Pflegeversicherung",fr:"Assurance dépendance"},
    "Social Security":{en:"Social Security",es:"Seguridad Social",de:"Sozialversicherung",fr:"Sécurité sociale"},
    "Social security":{en:"Social security",es:"Seguridad Social",de:"Sozialversicherung",fr:"Sécurité sociale"},
    "Social insurance":{en:"Social insurance",es:"Seguro social",de:"Sozialversicherung",fr:"Assurance sociale"},
    "Social & health":{en:"Social and health",es:"Seguridad social y salud",de:"Sozial- und Krankenversicherung",fr:"Assurance sociale et maladie"},
    "Pension contribution":{en:"Pension contribution",es:"Cotización de pensión",de:"Rentenbeitrag",fr:"Cotisation retraite"},
    "Labour market contribution":{en:"Labour-market contribution",es:"Contribución laboral",de:"Arbeitsmarktbeitrag",fr:"Contribution au marché du travail"},
    "National insurance (included in tax)":{en:"National insurance (included in tax)",es:"Seguros nacionales (incluidos)",de:"Volksversicherung (enthalten)",fr:"Assurance nationale (incluse)"},
  };
  return dictionary[label]?.[locale] ?? label;
}
