import type { Locale } from "./i18n";

const en = {
  brand: "ClearSalary", tag: "International salary calculator", title: "See what you actually take home.", sub: "Country-specific tax estimates, explained clearly.",
  country: "Country", gross: "Gross salary", monthly: "Monthly", annual: "Annual", hours: "Weekly hours (optional)", net: "Estimated net salary", annualNet: "Annual net", hour: "Net / hour", deductions: "Total deductions", keep: "You keep", breakdown: "Your salary breakdown", precise: "Get a more precise result", taxYear: "Tax year", updated: "Last checked", min: "Minimum wage check", below: "This gross hourly rate is below the legal minimum wage.", above: "This gross hourly rate is at or above the legal minimum wage.", method: "Sources & methodology", how: "How the estimate works", copy: "A transparent estimate based on the selected country’s progressive tax rules, allowances, tax credits and employee social contributions. It is not tax advice.", examples: "Popular salary examples", faq: "Frequently asked questions", q1: "Is this result exact?", a1: "It is a practical estimate. Your final payslip may change with region, family situation, benefits, deductions and employer payroll rules.", q2: "Why is there one result?", a2: "We apply a documented default profile for each country, then let you refine the inputs without showing an unhelpful range.", ad: "Advertisement space", search: "Search countries", explore: "Explore by country", noMinimum: "No national minimum wage", hourUnit: "hour", monthUnit: "month", grossShort: "gross", netShort: "net", data: "2026 data", estimate: "Estimate for information only", age: "Age", children: "Children", marital: "Marital status", single: "Single", married: "Married", taxClass: "Tax class", church: "Church tax", stateGroup: "Federal state", publicHealth: "Public health insurance", privateHealth: "Private health estimate", health: "Health insurance", region: "Region", average: "Average", lower: "Lower-tax region", higher: "Higher-tax region", contract: "Contract", permanent: "Permanent", temporary: "Temporary", filing: "Filing status", joint: "Married filing jointly", head: "Head of household", stateTax: "State income tax", canton: "Canton", province: "Province", assumptions: "These fields update the calculation instantly.", netLabel: "Net", deductionsLabel: "Deductions"
};

export type UiText = typeof en;

const es: UiText = {
  brand: "ClearSalary", tag: "Calculadora internacional de salarios", title: "Descubre cuánto dinero te queda realmente.", sub: "Estimaciones fiscales por país, explicadas con claridad.",
  country: "País", gross: "Salario bruto", monthly: "Mensual", annual: "Anual", hours: "Horas semanales (opcional)", net: "Salario neto estimado", annualNet: "Neto anual", hour: "Neto / hora", deductions: "Deducciones totales", keep: "Te queda", breakdown: "Desglose de tu salario", precise: "Obtener un resultado más preciso", taxYear: "Año fiscal", updated: "Última revisión", min: "Comprobación del salario mínimo", below: "El salario bruto por hora está por debajo del salario mínimo legal.", above: "El salario bruto por hora es igual o superior al salario mínimo legal.", method: "Fuentes y metodología", how: "Cómo funciona la estimación", copy: "Una estimación transparente basada en las reglas fiscales progresivas, mínimos, deducciones y cotizaciones del trabajador. No es asesoramiento fiscal.", examples: "Ejemplos de salarios", faq: "Preguntas frecuentes", q1: "¿El resultado es exacto?", a1: "Es una estimación práctica. La nómina final puede variar según región, situación familiar, beneficios, deducciones y reglas de nómina.", q2: "¿Por qué se muestra un único resultado?", a2: "Aplicamos un perfil predeterminado documentado para cada país y permitimos afinarlo sin mostrar un intervalo poco útil.", ad: "Espacio publicitario", search: "Buscar países", explore: "Explorar por país", noMinimum: "Sin salario mínimo nacional", hourUnit: "hora", monthUnit: "mes", grossShort: "brutos", netShort: "netos", data: "Datos de 2026", estimate: "Estimación meramente informativa", age: "Edad", children: "Hijos", marital: "Estado civil", single: "Soltero/a", married: "Casado/a", taxClass: "Clase fiscal", church: "Impuesto eclesiástico", stateGroup: "Estado federado", publicHealth: "Seguro médico público", privateHealth: "Estimación de seguro privado", health: "Seguro médico", region: "Región", average: "Promedio", lower: "Región con menor tributación", higher: "Región con mayor tributación", contract: "Contrato", permanent: "Indefinido", temporary: "Temporal", filing: "Estado de declaración", joint: "Declaración conjunta", head: "Cabeza de familia", stateTax: "Impuesto estatal", canton: "Cantón", province: "Provincia", assumptions: "Estos campos actualizan el cálculo al instante.", netLabel: "Neto", deductionsLabel: "Deducciones"
};

const de: UiText = {
  brand: "ClearSalary", tag: "Internationaler Gehaltsrechner", title: "Sieh, was von deinem Gehalt wirklich übrig bleibt.", sub: "Länderspezifische Steuerberechnungen, klar erklärt.",
  country: "Land", gross: "Bruttogehalt", monthly: "Monatlich", annual: "Jährlich", hours: "Wochenstunden (optional)", net: "Geschätztes Nettogehalt", annualNet: "Netto pro Jahr", hour: "Netto / Stunde", deductions: "Gesamtabzüge", keep: "Dir bleiben", breakdown: "Aufschlüsselung deines Gehalts", precise: "Genaueres Ergebnis erhalten", taxYear: "Steuerjahr", updated: "Zuletzt geprüft", min: "Mindestlohnprüfung", below: "Der Bruttostundenlohn liegt unter dem gesetzlichen Mindestlohn.", above: "Der Bruttostundenlohn entspricht mindestens dem gesetzlichen Mindestlohn.", method: "Quellen und Methodik", how: "So funktioniert die Schätzung", copy: "Eine transparente Schätzung anhand progressiver Steuern, Freibeträge, Gutschriften und Arbeitnehmerbeiträge. Keine Steuerberatung.", examples: "Beliebte Gehaltsbeispiele", faq: "Häufige Fragen", q1: "Ist das Ergebnis exakt?", a1: "Es ist eine praxisnahe Schätzung. Die tatsächliche Abrechnung kann je nach Region, Familie, Leistungen und Arbeitgeber abweichen.", q2: "Warum wird nur ein Ergebnis angezeigt?", a2: "Wir verwenden ein dokumentiertes Standardprofil und ermöglichen eine Verfeinerung, ohne eine wenig hilfreiche Spanne anzuzeigen.", ad: "Werbefläche", search: "Länder suchen", explore: "Nach Land entdecken", noMinimum: "Kein nationaler gesetzlicher Mindestlohn", hourUnit: "Stunde", monthUnit: "Monat", grossShort: "brutto", netShort: "netto", data: "Daten 2026", estimate: "Unverbindliche Schätzung", age: "Alter", children: "Kinder", marital: "Familienstand", single: "Ledig", married: "Verheiratet", taxClass: "Steuerklasse", church: "Kirchensteuer", stateGroup: "Bundesland", publicHealth: "Gesetzliche Krankenversicherung", privateHealth: "Private Krankenversicherung (Schätzung)", health: "Krankenversicherung", region: "Region", average: "Durchschnitt", lower: "Niedrigere Steuerregion", higher: "Höhere Steuerregion", contract: "Vertrag", permanent: "Unbefristet", temporary: "Befristet", filing: "Veranlagungsstatus", joint: "Zusammenveranlagung", head: "Haushaltsvorstand", stateTax: "Bundesstaatsteuer", canton: "Kanton", province: "Provinz", assumptions: "Diese Angaben aktualisieren die Berechnung sofort.", netLabel: "Netto", deductionsLabel: "Abzüge"
};

const fr: UiText = {
  brand: "ClearSalary", tag: "Calculateur de salaire international", title: "Découvrez ce que vous gagnez réellement.", sub: "Des estimations fiscales par pays, expliquées clairement.",
  country: "Pays", gross: "Salaire brut", monthly: "Mensuel", annual: "Annuel", hours: "Heures par semaine (facultatif)", net: "Salaire net estimé", annualNet: "Net annuel", hour: "Net / heure", deductions: "Total des prélèvements", keep: "Vous gardez", breakdown: "Détail de votre salaire", precise: "Obtenir un résultat plus précis", taxYear: "Année fiscale", updated: "Dernière vérification", min: "Vérification du salaire minimum", below: "Le salaire horaire brut est inférieur au minimum légal.", above: "Le salaire horaire brut est égal ou supérieur au minimum légal.", method: "Sources et méthodologie", how: "Comment fonctionne l’estimation", copy: "Une estimation transparente fondée sur les barèmes progressifs, abattements, crédits d’impôt et cotisations salariales. Ceci ne constitue pas un conseil fiscal.", examples: "Exemples de salaires", faq: "Questions fréquentes", q1: "Le résultat est-il exact ?", a1: "Il s’agit d’une estimation pratique. La fiche de paie finale peut varier selon la région, la famille, les avantages et les règles de paie.", q2: "Pourquoi un seul résultat ?", a2: "Nous appliquons un profil standard documenté et permettons de l’affiner sans afficher une fourchette peu utile.", ad: "Espace publicitaire", search: "Rechercher un pays", explore: "Explorer par pays", noMinimum: "Aucun salaire minimum national", hourUnit: "heure", monthUnit: "mois", grossShort: "brut", netShort: "net", data: "Données 2026", estimate: "Estimation à titre informatif", age: "Âge", children: "Enfants", marital: "Situation familiale", single: "Célibataire", married: "Marié(e)", taxClass: "Classe fiscale", church: "Impôt cultuel", stateGroup: "État fédéré", publicHealth: "Assurance maladie publique", privateHealth: "Assurance privée estimée", health: "Assurance maladie", region: "Région", average: "Moyenne", lower: "Région moins imposée", higher: "Région plus imposée", contract: "Contrat", permanent: "Permanent", temporary: "Temporaire", filing: "Statut fiscal", joint: "Déclaration commune", head: "Chef de famille", stateTax: "Impôt d’État", canton: "Canton", province: "Province", assumptions: "Ces champs actualisent immédiatement le calcul.", netLabel: "Net", deductionsLabel: "Prélèvements"
};

export const uiText: Record<Locale, UiText> = { en, es, de, fr };
